language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - extra-android-m2repository
    - platform-tools
    - build-tools-24.0.2
    - android-24

jdk:
    - oraclejdk8

script:
    - ./gradlew build connectedCheck

before_install:
    - chmod +x gradlew

branches:
  only:
    - master